# Generated by Django 3.0.4 on 2020-03-25 14:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('BrandID', models.AutoField(primary_key=True, serialize=False)),
                ('Brand', models.CharField(max_length=64, unique=True)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Weight', models.DecimalField(decimal_places=0, max_digits=4)),
                ('Image', models.ImageField(default='tobacco_default.png', upload_to='brand_pics')),
            ],
        ),
        migrations.CreateModel(
            name='TobaccoList',
            fields=[
                ('TobaccoID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=64)),
                ('Taste', models.CharField(max_length=64)),
                ('Comment', models.TextField(blank=True, null=True)),
                ('Date_Posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('Image', models.ImageField(default='tobacco_default.png', upload_to='tobacco_pics')),
                ('QTaste', models.CharField(choices=[('?', '?'), ('Sehr Gut', 'Sehr Gut'), ('Gut', 'Gut'), ('Befriedigend ', 'Befriedigend '), ('Ausreichend ', 'Ausreichend '), ('Mangelhaft ', 'Mangelhaft '), ('Ungenügend', 'Ungenügend')], default='?', max_length=16)),
                ('QSmoke', models.CharField(choices=[('?', '?'), ('Sehr Gut', 'Sehr Gut'), ('Gut', 'Gut'), ('Befriedigend ', 'Befriedigend '), ('Ausreichend ', 'Ausreichend '), ('Mangelhaft ', 'Mangelhaft '), ('Ungenügend', 'Ungenügend')], default='?', max_length=16)),
                ('QCut', models.CharField(choices=[('?', '?'), ('Sehr Gut', 'Sehr Gut'), ('Gut', 'Gut'), ('Befriedigend ', 'Befriedigend '), ('Ausreichend ', 'Ausreichend '), ('Mangelhaft ', 'Mangelhaft '), ('Ungenügend', 'Ungenügend')], default='?', max_length=16)),
                ('Inventory', models.BooleanField(default=True)),
                ('Wish', models.BooleanField(default=False)),
                ('BrandID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tobacco.Brands')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('WishlistID', models.AutoField(primary_key=True, serialize=False)),
                ('Priority', models.CharField(choices=[('Hoch', 'Hoch'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=8)),
                ('TobaccoID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tobacco.TobaccoList')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('InventoryID', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField(choices=[(0, '0%'), (10, '10%'), (20, '20%'), (30, '30%'), (40, '40%'), (50, '50%'), (60, '60%'), (70, '70%'), (80, '80%'), (90, '90%'), (100, '100%')], default=0)),
                ('TobaccoID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tobacco.TobaccoList')),
            ],
        ),
    ]
