# Generated by Django 3.0.5 on 2020-04-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tobacco', '0002_auto_20200327_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='Quantity',
            field=models.IntegerField(choices=[(0, '0%'), (10, '10%'), (20, '20%'), (30, '30%'), (40, '40%'), (50, '50%'), (60, '60%'), (70, '70%'), (80, '80%'), (90, '90%'), (100, '100%')], default=100),
        ),
    ]
